// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exercises.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (name, description)
VALUES ($1, $2)
RETURNING id, name, description
`

type CreateExerciseParams struct {
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.Name, arg.Description)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getExercise = `-- name: GetExercise :one
SELECT id, name, description FROM exercises
WHERE id = $1
`

func (q *Queries) GetExercise(ctx context.Context, id int32) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
