// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: logs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (weight, reps, logs_order, exercise_id, set_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, last_modified_at, weight, reps, logs_order, exercise_id, set_id
`

type CreateLogParams struct {
	Weight     pgtype.Float8
	Reps       int32
	LogsOrder  int32
	ExerciseID int32
	SetID      int64
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, createLog,
		arg.Weight,
		arg.Reps,
		arg.LogsOrder,
		arg.ExerciseID,
		arg.SetID,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.Weight,
		&i.Reps,
		&i.LogsOrder,
		&i.ExerciseID,
		&i.SetID,
	)
	return i, err
}

const getLog = `-- name: GetLog :one
SELECT id, created_at, last_modified_at, weight, reps, logs_order, exercise_id, set_id FROM logs
WHERE id = $1
`

func (q *Queries) GetLog(ctx context.Context, id int64) (Log, error) {
	row := q.db.QueryRow(ctx, getLog, id)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.Weight,
		&i.Reps,
		&i.LogsOrder,
		&i.ExerciseID,
		&i.SetID,
	)
	return i, err
}
