// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID           int32
	Name         string
	Type         string
	Resources    []string
	Description  pgtype.Text
	MuscleGroups []string
}

type Log struct {
	ID             int64
	CreatedAt      pgtype.Timestamp
	LastModifiedAt pgtype.Timestamp
	Weight         pgtype.Float8
	Reps           int32
	LogsOrder      int16
	ExerciseID     int32
	SetID          int64
}

type Session struct {
	ID              int64
	Date            pgtype.Date
	TimeStart       pgtype.Timestamp
	DurationMinutes int16
	UserID          pgtype.UUID
}

type Set struct {
	ID        int64
	SetOrder  int16
	RestTime  pgtype.Int4
	SessionID int64
}

type User struct {
	ID             pgtype.UUID
	Username       string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
	Country        pgtype.Text
	Birthday       pgtype.Date
}
