// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID          int32
	Name        string
	Description pgtype.Text
}

type Log struct {
	ID             int64
	CreatedAt      pgtype.Timestamp
	LastModifiedAt pgtype.Timestamp
	Weight         pgtype.Float8
	Reps           int32
	LogsOrder      int32
	ExerciseID     int32
	SetID          int64
}

type RefreshToken struct {
	Token     string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
	RevokedAt pgtype.Timestamp
	UserID    uuid.UUID
}

type Session struct {
	ID              uuid.UUID
	Name            string
	Date            pgtype.Date
	StartTimestamp  pgtype.Timestamp
	DurationMinutes pgtype.Int2
	UserID          uuid.UUID
}

type Set struct {
	ID         int64
	SetOrder   int32
	RestTime   pgtype.Int4
	SessionID  uuid.UUID
	ExerciseID int32
}

type User struct {
	ID             uuid.UUID
	Username       string
	HashedPassword string
	IsAdmin        pgtype.Bool
	CreatedAt      pgtype.Timestamp
	Country        pgtype.Text
	Birthday       pgtype.Date
}
