// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (name, date, start_timestamp, duration_minutes, user_id)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, date, start_timestamp, duration_minutes, user_id
`

type CreateSessionParams struct {
	Name            string
	Date            pgtype.Date
	StartTimestamp  pgtype.Timestamp
	DurationMinutes pgtype.Int2
	UserID          pgtype.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Name,
		arg.Date,
		arg.StartTimestamp,
		arg.DurationMinutes,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.StartTimestamp,
		&i.DurationMinutes,
		&i.UserID,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, name, date, start_timestamp, duration_minutes, user_id FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.StartTimestamp,
		&i.DurationMinutes,
		&i.UserID,
	)
	return i, err
}

const getSessionOwnerID = `-- name: GetSessionOwnerID :one
SELECT user_id FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionOwnerID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSessionOwnerID, id)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT id, name, date, start_timestamp, duration_minutes, user_id FROM sessions
WHERE user_id = $1
ORDER BY date DESC
`

func (q *Queries) GetSessionsByUserID(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.StartTimestamp,
			&i.DurationMinutes,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET name = $1,
    date = $2,
    start_timestamp = $3,
    duration_minutes = $4
WHERE id = $5
RETURNING id, name, date, start_timestamp, duration_minutes, user_id
`

type UpdateSessionParams struct {
	Name            string
	Date            pgtype.Date
	StartTimestamp  pgtype.Timestamp
	DurationMinutes pgtype.Int2
	ID              pgtype.UUID
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.Name,
		arg.Date,
		arg.StartTimestamp,
		arg.DurationMinutes,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.StartTimestamp,
		&i.DurationMinutes,
		&i.UserID,
	)
	return i, err
}
