// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSet = `-- name: CreateSet :one
INSERT INTO sets (set_order, rest_time, session_id, exercise_id)
VALUES ($1, $2, $3, $4)
RETURNING id, set_order, rest_time, session_id, exercise_id
`

type CreateSetParams struct {
	SetOrder   int32
	RestTime   pgtype.Int4
	SessionID  pgtype.UUID
	ExerciseID int32
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (Set, error) {
	row := q.db.QueryRow(ctx, createSet,
		arg.SetOrder,
		arg.RestTime,
		arg.SessionID,
		arg.ExerciseID,
	)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.SetOrder,
		&i.RestTime,
		&i.SessionID,
		&i.ExerciseID,
	)
	return i, err
}

const getSet = `-- name: GetSet :one
SELECT id, set_order, rest_time, session_id, exercise_id FROM sets
WHERE id = $1
`

func (q *Queries) GetSet(ctx context.Context, id int64) (Set, error) {
	row := q.db.QueryRow(ctx, getSet, id)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.SetOrder,
		&i.RestTime,
		&i.SessionID,
		&i.ExerciseID,
	)
	return i, err
}
