// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sets.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSet = `-- name: CreateSet :one
INSERT INTO sets (set_order, rest_time, session_id, exercise_id)
VALUES ($1, $2, $3, $4)
RETURNING id, set_order, rest_time, session_id, exercise_id
`

type CreateSetParams struct {
	SetOrder   int32
	RestTime   pgtype.Int4
	SessionID  uuid.UUID
	ExerciseID int32
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (Set, error) {
	row := q.db.QueryRow(ctx, createSet,
		arg.SetOrder,
		arg.RestTime,
		arg.SessionID,
		arg.ExerciseID,
	)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.SetOrder,
		&i.RestTime,
		&i.SessionID,
		&i.ExerciseID,
	)
	return i, err
}

const deleteSet = `-- name: DeleteSet :one
DELETE FROM sets
WHERE id = $1
RETURNING id, set_order, rest_time, session_id, exercise_id
`

func (q *Queries) DeleteSet(ctx context.Context, id int64) (Set, error) {
	row := q.db.QueryRow(ctx, deleteSet, id)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.SetOrder,
		&i.RestTime,
		&i.SessionID,
		&i.ExerciseID,
	)
	return i, err
}

const getSet = `-- name: GetSet :one
SELECT id, set_order, rest_time, session_id, exercise_id FROM sets
WHERE id = $1
`

func (q *Queries) GetSet(ctx context.Context, id int64) (Set, error) {
	row := q.db.QueryRow(ctx, getSet, id)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.SetOrder,
		&i.RestTime,
		&i.SessionID,
		&i.ExerciseID,
	)
	return i, err
}

const getSetOwnerID = `-- name: GetSetOwnerID :one
SELECT sessions.user_id FROM sets
JOIN sessions
ON sets.session_id = sessions.id
WHERE sets.id = $1
`

func (q *Queries) GetSetOwnerID(ctx context.Context, id int64) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSetOwnerID, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getSetsBySessionIDs = `-- name: GetSetsBySessionIDs :many
SELECT id, set_order, rest_time, session_id, exercise_id FROM sets
WHERE session_id = ANY($1::uuid[])
ORDER BY session_id, set_order
`

func (q *Queries) GetSetsBySessionIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Set, error) {
	rows, err := q.db.Query(ctx, getSetsBySessionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.SetOrder,
			&i.RestTime,
			&i.SessionID,
			&i.ExerciseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
