// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO users (id, username, is_admin, country, hashed_password, birthday)
VALUES (gen_random_uuid(), $1, TRUE, $2, $3, $4)
RETURNING id, username, hashed_password, is_admin, created_at, country, birthday
`

type CreateAdminParams struct {
	Username       string
	Country        pgtype.Text
	HashedPassword string
	Birthday       pgtype.Date
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Username,
		arg.Country,
		arg.HashedPassword,
		arg.Birthday,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.Country,
		&i.Birthday,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, country, hashed_password, birthday)
VALUES (
    gen_random_uuid(), $1, $2, $3, $4
)
RETURNING id, username, hashed_password, is_admin, created_at, country, birthday
`

type CreateUserParams struct {
	Username       string
	Country        pgtype.Text
	HashedPassword string
	Birthday       pgtype.Date
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Country,
		arg.HashedPassword,
		arg.Birthday,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.Country,
		&i.Birthday,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, username, hashed_password, is_admin, created_at, country, birthday
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.Country,
		&i.Birthday,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, hashed_password, is_admin, created_at, country, birthday FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.Country,
		&i.Birthday,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, hashed_password, is_admin, created_at, country, birthday FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.Country,
		&i.Birthday,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, hashed_password, is_admin, created_at, country, birthday FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.Country,
			&i.Birthday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
